apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chobu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: artbit-registry
      containers:
        - name: backend
          image: cr.artbit.com.pl/irek/cho_back:0.1
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chobu-secret
                  key: BACKEND_DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: chobu-config
                  key: BACKEND_REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chobu-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chobu
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: chobu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      imagePullSecrets:
        - name: artbit-registry
      containers:
        - name: notification
          image: cr.artbit.com.pl/irek/cho_info:0.1
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chobu-secret
                  key: INFO_DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: chobu-config
                  key: INFO_REDIS_URL
