apiVersion: v1
kind: Secret
metadata:
  name: artbit-registry
  namespace: chobu
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "cr.artbit.com.pl": {
          "username": "irek",
          "password": "Atadj1006!",
          "auth": "aXJlawpBdGFkajEwMDYh"
        }
      }
    }
